=== Fody/FodyAddinSamples/Samples/FodyWeavers.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- This file was generated by Fody. Manual changes to this file will be lost when your project is rebuilt. -->
  <xs:element name="Weavers">
    <xs:complexType>
      <xs:all>
        <xs:element name="Visualize" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Virtuosity" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Validar" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Resourcer" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Publicize" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="PropertyChanging" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="PropertyChanged" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="InjectOnPropertyNameChanged" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if the On_PropertyName_Changed feature is enabled.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="TriggerDependentProperties" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if the Dependent properties feature is enabled.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="EnableIsChangedProperty" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if the IsChanged property feature is enabled.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="EventInvokerNames" type="xs:string">
              <xs:annotation>
                <xs:documentation>Used to change the name of the method that fires the notify event. This is a string that accepts multiple values in a comma separated form.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="CheckForEquality" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if equality checks should be inserted. If false, equality checking will be disabled for the project.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="CheckForEqualityUsingBaseEquals" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if equality checks should use the Equals method resolved from the base class.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UseStaticEqualsFromBase" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to control if equality checks should use the static Equals method resolved from the base class.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="SuppressWarnings" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to turn off build warnings from this weaver.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="SuppressOnPropertyNameChangedWarning" type="xs:boolean">
              <xs:annotation>
                <xs:documentation>Used to turn off build warnings about mismatched On_PropertyName_Changed methods.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="Obsolete" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="ModuleInit" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="MethodTimer" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Janitor" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Ionad" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="InfoOf" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="ExtraConstraints" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Equatable" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="EmptyConstructor" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Caseless" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="BasicFodyAddin" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="Namespace" type="xs:string">
              <xs:annotation>
                <xs:documentation>Namespace to use for the injected type</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="AsyncErrorHandler" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Anotar.Serilog" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Anotar.NLog" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Anotar.Custom" minOccurs="0" maxOccurs="1" type="xs:anyType" />
        <xs:element name="Anotar.CommonLogging" minOccurs="0" maxOccurs="1" type="xs:anyType" />
      </xs:all>
      <xs:attribute name="VerifyAssembly" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>'true' to run assembly verification (PEVerify) on the target assembly after all weavers have been executed.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="VerifyIgnoreCodes" type="xs:string">
        <xs:annotation>
          <xs:documentation>A comma-separated list of error codes that can be safely ignored in assembly verification.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="GenerateXsd" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>'false' to turn off automatic generation of the XML Schema file.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Fody/FodyAddinSamples/Samples/FodyWeavers.xml
<Weavers VerifyAssembly="true"
         VerifyIgnoreCodes="0x80131869"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Anotar.Serilog />
  <Anotar.NLog />
  <Anotar.Custom />
  <Anotar.CommonLogging />
  <AsyncErrorHandler />
  <BasicFodyAddin />
  <Caseless />
  <EmptyConstructor />
  <ExtraConstraints />
  <Equatable />
  <InfoOf />
  <Ionad />
  <Janitor />
  <MethodTimer />
  <ModuleInit />
  <Obsolete />
  <PropertyChanging />
  <PropertyChanged />
  <Validar />
  <Resourcer />
  <Publicize />
  <Virtuosity />
  <Visualize />
</Weavers>
